# Python Django
# Test a Django project on multiple versions of Python.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

variables:
  ConnectedServiceName: 'MyAzureResourceManagerServiceConnection'
  WebAppName: 'clt-homicide-uat'

trigger:
- master

pool:
  name: Hosted Ubuntu 1604

steps:
- task: UsePythonVersion@0
  displayName: 'PyVer'
  inputs:
    versionSpec: '3.6'
    architecture: 'x64'

- script: |    
    python3.6 -m venv hom36env
    source hom36env/bin/activate
    pip3 install setuptools
    pip3 install -r requirements.txt
  displayName: 'Depend'

- script: |
    python3.6 manage.py test tracker --no-input
  displayName: 'Run tests'

- script: |     
    pytest --junitxml=reports/django-basic.xml     
  displayName: 'Run pytests'

- task: ArchiveFiles@2
  displayName: 'Archiver'
  inputs:
    #'$(System.DefaultWorkingDirectory)/Application
    # rootFolderOrFile: '$(Build.SourcesDirectory)'
    # rootFolderOrFile: '$(Build.BinariesDirectory)'
    rootFolderOrFile: '*'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/Application$(Build.BuildId).zip'
    replaceExistingArchive: true
    verbose: # Optional

- task: AzureRMWebAppDeployment@4
  displayName: Azure App Service Deploy
  inputs:
    appType: webAppLinux
    RuntimeStack: 'PYTHON|3.6'
    ConnectedServiceName: $(ConnectedServiceName)
    WebAppName: $(WebAppName)
    Package: '$(Build.ArtifactStagingDirectory)/Application$(Build.BuildId).zip'

    # # why django isn't in path.. ?
    ScriptType: Inline Script
    InlineScript:
      pip3 list
#      pip3 install -r requirements.txt

#    StartupCommand: 'gunicorn --bind=0.0.0.0 --timeout 600 homicide.wsgi'
    StartupCommand: 'python3 manage.py runserver'

