# Generated by Django 2.2.3 on 2019-07-14 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Homicide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('street', models.CharField(max_length=80)),
                ('intersection', models.CharField(max_length=120)),
                ('zipcode', models.CharField(max_length=5)),
                ('gender', models.CharField(max_length=1)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=250)),
                ('homicide', models.ManyToManyField(to='tracker.Homicide')),
            ],
        ),
    ]
