# Generated by Django 2.2.2 on 2019-07-15 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=250)),
                ('url', models.CharField(max_length=250)),
                ('sentiment', models.CharField(blank=True, default='NA', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Homicide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField(blank=True, default='01:00')),
                ('street', models.CharField(blank=True, default='', max_length=80)),
                ('intersection', models.CharField(blank=True, default='', max_length=120)),
                ('zipcode', models.CharField(blank=True, default='', max_length=5)),
                ('gender', models.CharField(blank=True, default='M', max_length=5)),
                ('age', models.IntegerField(blank=True, default=0)),
                ('articles', models.ManyToManyField(to='tracker.Article')),
            ],
        ),
    ]
