# Generated by Django 2.2.2 on 2019-07-15 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homicide',
            name='articles',
            field=models.ManyToManyField(blank=True, to='tracker.Article'),
        ),
    ]
