# Generated by Django 2.2.3 on 2019-07-14 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homicide',
            name='time',
            field=models.TimeField(blank=True, default='01:00'),
        ),
        migrations.AlterField(
            model_name='homicide',
            name='age',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='homicide',
            name='gender',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='homicide',
            name='intersection',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='homicide',
            name='street',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='homicide',
            name='zipcode',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
    ]
