# Generated by Django 2.2.2 on 2019-07-15 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_auto_20190714_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='homicide',
            name='count',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='homicide',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('O', 'Other or Unknown')], default='M', max_length=1),
        ),
    ]
