# Generated by Django 2.2.3 on 2019-07-14 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_auto_20190714_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homicide',
            name='age',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='homicide',
            name='gender',
            field=models.CharField(blank=True, default='M', max_length=5),
        ),
    ]
