# Generated by Django 2.2.2 on 2019-07-15 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_auto_20190714_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='homicide',
            name='name',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
    ]
