# Generated by Django 2.2.3 on 2019-07-19 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_homicide_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='homicide',
            name='maplink',
            field=models.CharField(blank=True, default='', max_length=180),
        ),
        migrations.AddField(
            model_name='homicide',
            name='reason',
            field=models.CharField(choices=[('D', 'Dispute'), ('G', 'Gang'), ('F', 'Family/Domestic'), ('O', 'Other or Unknown')], default='M', max_length=1),
        ),
    ]
