# Generated by Django 2.2.3 on 2019-07-19 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_auto_20190718_2006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homicide',
            name='reason',
        ),
        migrations.AddField(
            model_name='homicide',
            name='method',
            field=models.CharField(choices=[('S', 'Stabbing'), ('G', 'Gun'), ('O', 'Other or Unknown')], default='O', max_length=1),
        ),
        migrations.AddField(
            model_name='homicide',
            name='motive',
            field=models.CharField(choices=[('D', 'Dispute'), ('G', 'Gang'), ('F', 'Family/Domestic'), ('O', 'Other or Unknown')], default='O', max_length=1),
        ),
    ]
