# Generated by Django 2.2.3 on 2019-07-19 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_auto_20190718_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='homicide',
            name='solved',
            field=models.CharField(choices=[('Y', 'N')], default='N', max_length=1),
        ),
    ]
