# Generated by Django 2.2.3 on 2019-07-19 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_homicide_solved'),
    ]

    operations = [
        migrations.AddField(
            model_name='homicide',
            name='mapiframe',
            field=models.CharField(blank=True, default='', max_length=180),
        ),
    ]
