# Generated by Django 2.2.3 on 2019-07-19 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_homicide_mapiframe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homicide',
            name='mapiframe',
            field=models.TextField(blank=True, default=''),
        ),
    ]
