# Generated by Django 2.2.3 on 2019-07-19 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_auto_20190719_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homicide',
            name='solved',
            field=models.CharField(choices=[('S', 'Solved'), ('U', 'Unsolved')], default='N', max_length=1),
        ),
    ]
