# Generated by Django 2.2.3 on 2019-07-19 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_auto_20190719_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='homicide',
            name='ethnicity',
            field=models.CharField(choices=[('A', 'Asian'), ('W', 'White'), ('B', 'Black'), ('H', 'Hispanic'), ('O', 'Other'), ('U', 'Unknown')], default='U', max_length=80),
        ),
        migrations.AddField(
            model_name='homicide',
            name='killer_age',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='homicide',
            name='killer_ethnicity',
            field=models.CharField(choices=[('A', 'Asian'), ('W', 'White'), ('B', 'Black'), ('H', 'Hispanic'), ('O', 'Other'), ('U', 'Unknown')], default='U', max_length=80),
        ),
        migrations.AddField(
            model_name='homicide',
            name='killer_gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('O', 'Other or Unknown')], default='M', max_length=1),
        ),
        migrations.AddField(
            model_name='homicide',
            name='killer_name',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
    ]
