# Generated by Django 2.2.3 on 2019-07-20 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0012_auto_20190719_1909'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homicide',
            old_name='killer_age',
            new_name='killerage',
        ),
        migrations.RenameField(
            model_name='homicide',
            old_name='killer_ethnicity',
            new_name='killerethnicity',
        ),
        migrations.RenameField(
            model_name='homicide',
            old_name='killer_gender',
            new_name='killergender',
        ),
        migrations.RenameField(
            model_name='homicide',
            old_name='killer_name',
            new_name='killername',
        ),
    ]
