# Generated by Django 2.2.2 on 2019-07-20 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0014_auto_20190719_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='homicide',
            name='location',
            field=models.CharField(choices=[('H', 'Home'), ('C', 'Car'), ('S', 'Street'), ('O', 'Other/Unknown')], default='U', max_length=1),
        ),
        migrations.AlterField(
            model_name='homicide',
            name='ethnicity',
            field=models.CharField(choices=[('A', 'Asian'), ('W', 'White'), ('B', 'Black'), ('H', 'Hispanic'), ('O', 'Other'), ('U', 'Unknown')], default='U', max_length=1),
        ),
        migrations.AlterField(
            model_name='homicide',
            name='killerethnicity',
            field=models.CharField(choices=[('A', 'Asian'), ('W', 'White'), ('B', 'Black'), ('H', 'Hispanic'), ('O', 'Other'), ('U', 'Unknown')], default='U', max_length=1),
        ),
    ]
