# Generated by Django 2.2.2 on 2019-07-20 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0015_auto_20190719_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homicide',
            name='solved',
            field=models.CharField(choices=[('S', 'Solved'), ('U', 'Unsolved')], default='U', max_length=1),
        ),
    ]
