# Generated by Django 2.2.3 on 2019-07-21 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0017_article_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homicide',
            name='maplink',
        ),
        migrations.AlterField(
            model_name='homicide',
            name='location',
            field=models.CharField(choices=[('H', 'Home'), ('C', 'Car'), ('S', 'Street'), ('O', 'Other/Unknown')], default='O', max_length=1),
        ),
    ]
