# Generated by Django 2.2.2 on 2019-07-21 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0019_auto_20190721_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homicide',
            name='ethnicity',
            field=models.CharField(choices=[('A', 'Asian'), ('W', 'White'), ('B', 'Black'), ('H', 'Hispanic'), ('O', 'Other or Unknown')], default='U', max_length=1),
        ),
        migrations.AlterField(
            model_name='homicide',
            name='killerethnicity',
            field=models.CharField(choices=[('A', 'Asian'), ('W', 'White'), ('B', 'Black'), ('H', 'Hispanic'), ('O', 'Other or Unknown')], default='U', max_length=1),
        ),
    ]
