# Generated by Django 2.2.2 on 2019-07-21 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0020_auto_20190721_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homicide',
            name='ethnicity',
            field=models.CharField(choices=[('A', 'Asian'), ('W', 'White'), ('B', 'Black'), ('H', 'Hispanic'), ('O', 'Other or Unknown')], default='O', max_length=1),
        ),
        migrations.AlterField(
            model_name='homicide',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('O', 'Other or Unknown')], default='O', max_length=1),
        ),
        migrations.AlterField(
            model_name='homicide',
            name='killerethnicity',
            field=models.CharField(choices=[('A', 'Asian'), ('W', 'White'), ('B', 'Black'), ('H', 'Hispanic'), ('O', 'Other or Unknown')], default='O', max_length=1),
        ),
        migrations.AlterField(
            model_name='homicide',
            name='killergender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('O', 'Other or Unknown')], default='O', max_length=1),
        ),
    ]
