# Generated by Django 2.2.3 on 2019-07-21 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0021_auto_20190721_0158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homicide',
            name='solved',
        ),
        migrations.RemoveField(
            model_name='homicide',
            name='zipcode',
        ),
    ]
