# Generated by Django 2.2.3 on 2019-07-30 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0023_historical'),
    ]

    operations = [
        migrations.AddField(
            model_name='historical',
            name='population',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
