# Generated by Django 2.2.3 on 2019-07-30 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0024_historical_population'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historical',
            name='year',
            field=models.IntegerField(),
        ),
    ]
